### ISSUE TITLE
[BUG] 点击推荐歌曲和榜单一直白屏

### ISSUE THREAD

**Issue by vgoer** [maotoumao/MusicFree#103]
**注意事项**
- [x] 确保该bug可能是软件的本身问题，不是由于插件导致（如搜索结果不全，无法导入等都属于插件问题）；如果是插件问题请去对应第三方插件仓库提issue。
- [x] 确保已经搜索过issue区，并阅读过QA

---

**问题描述**
点击推荐歌曲和榜单一直白屏

**截图**
![微信图片_20231026100357](https://github.com/maotoumao/MusicFree/assets/97332512/6b3035d9-60f3-4ff8-9125-ba74a57974b8)
![微信图片_20231026100350](https://github.com/maotoumao/MusicFree/assets/97332512/3e24a6d2-e53e-49f2-9f0a-cb382734a1e0)
![微信图片_20231026100343](https://github.com/maotoumao/MusicFree/assets/97332512/1e6a28a0-4ad0-452b-938b-98056b5e9a28)

**其他信息:**
 - OS: [e.g. Android12]
 - 版本号 [e.g. v0.1.0-alpha.0]

**Comment by KamFlydual** [comment]
[0.1.1-alpha.0]白屏 换成0.1.0就好了
