### ISSUE TITLE
[FEATURE] 播放的时候这个地方没法控制

### ISSUE THREAD

**Issue by a52948** [maotoumao/MusicFree#106]
![5d7efd206c758f4c13c6217b73fb3d1](https://github.com/maotoumao/MusicFree/assets/26563810/f55f98ee-6c0b-4d88-9e7b-2f7bd358d6fb)

**Comment by akers4238** [comment]
这个我知道，目前只有b站播放可以看到播放进度，把听的音乐换成b站那的就行了（我小米能行）
