### ISSUE TITLE
每个歌单限制50首  是否能增加到几百首

### ISSUE THREAD

**Issue by tiyuban123** [maotoumao/MusicFree#107]
每个歌单限制50首  是否能增加到几百首 或者自定义歌单下音乐最大数量

**Comment by maotoumao** [comment]
没有这种限制呀，啥情况下会出现歌单限制50首呢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月30日 09:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 每个歌单限制50首  是否能增加到几百首 (Issue #107) |

每个歌单限制50首 是否能增加到几百首 或者自定义歌单下音乐最大数量

**Comment by javelinki** [comment]
把歌单往下拉，拉到底，再收藏就可以收藏歌单内全部歌曲
