### ISSUE TITLE
在华为平板上的问题

### ISSUE THREAD

**Issue by lzb-libra** [maotoumao/MusicFree#12]
我将该app安装到我的华为pad上，发现样式完全乱套了，插件导入也不能使用，组件ui超出屏幕显示宽度等问题，不知道能不能兼容一下

**Comment by maotoumao** [comment]
是matepad11嘛

平板和横屏样式确实没做兼容，近期开始做～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月01日 11:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] huawei matebook 11 (Issue #12) |

我将该app安装到我的华为pad上，发现样式完全乱套了，不知道能不能兼容一下
