### ISSUE TITLE
[BUG] 软件搜索时只展示了第一页的歌曲，无法上滑展示第二页及后面的歌曲

### ISSUE THREAD

**Issue by elevenChen2019** [maotoumao/MusicFree#121]
**问题描述**
软件搜索时只展示了第一页的歌曲，无法上滑展示第二页及后面的歌曲

**预期行为**
屏幕上滑时，应该展示第二页及之后的歌曲

**截图**
![41abf8194ea394a8e86a8f94cab5fe7](https://github.com/maotoumao/MusicFree/assets/54252871/dd1f3bee-4bf4-498e-b34e-c98c0ee4b732)
![image](https://github.com/maotoumao/MusicFree/assets/54252871/3dc0c1e2-6cb4-4b8e-a0e9-e03cb847aff5)

**其他信息:**
 - OS: [ColorOS13.1 Android13]
 - 版本号 [v0.1.1-alpha.0]

**Comment by maotoumao** [comment]
我试着可以继续下滑～有可能是网络问题请求失败了 再试试吧～

这块体验确实不是很好 我之后找时间优化一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月13日 16:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] [BUG] 软件搜索时只展示了第一页的歌曲，无法上滑展示第二页及后面的歌曲 (Issue #121) |

问题描述
软件搜索时只展示了第一页的歌曲，无法上滑展示第二页及后面的歌曲

预期行为
屏幕上滑时，应该展示第二页及之后的歌曲

截图



其他信息:

OS: [ColorOS13.1 Android13]
版本号 [v0.1.1-alpha.0]
