### ISSUE TITLE
[FEATURE]横屏设备需要添加一个回到桌面的按钮， 如果方便的话

### ISSUE THREAD

**Issue by qdpatriotcn** [maotoumao/MusicFree#124]
**注意事项**
- [ ] 确保已经阅读过ReadMe并*了解本软件的定位*
- [ ] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
软件支持横屏设备，在车机上使用，可不可以加一个回到桌面的按钮。
![Screenshot_20231116-150834_MusicFree](https://github.com/maotoumao/MusicFree/assets/105200583/c9e35ef9-ff72-40c9-80e9-ac23205c2e73)

**替代方案**
无论如何，都非常感谢作者的付出。

**其他信息**
能分享给我们这么好的软件

**Comment by maotoumao** [comment]
好办～ 下个版本就加上

**Comment by qdpatriotcn** [comment]
> 好办～ 下个版本就加上

回复超快。感谢。希望越来越好。💯
