### ISSUE TITLE
[BUG] 桌面端导出的json文件，以url的方式导入到手机端报错

### ISSUE THREAD

**Issue by showyoulove1990** [maotoumao/MusicFree#127]
**注意事项**
- [x] 确保该bug可能是软件的本身问题，不是由于插件导致（如搜索结果不全，无法导入等都属于插件问题）；如果是插件问题请去对应第三方插件仓库提issue。
- [x] 确保已经搜索过issue区，并阅读过QA

---

**问题描述**
桌面版导出的歌曲列表json文件存放在服务器上面，通过url的方式导入到手机端，报错。看错误信息应该是解析的时候，有东西未定义

**详细的复现步骤**
按步骤详细描述一下触发bug的特定行为：

**预期行为**
描述一下预期正确的行为是什么样的

**截图**
![image](https://github.com/maotoumao/MusicFree/assets/29604166/bdc8fe9d-4cda-443a-89d1-56bb737dec41)

![image](https://github.com/maotoumao/MusicFree/assets/29604166/90d53b1f-cdb9-4017-b89a-064de8fd2e1a)

**其他信息:**
 - OS: [e.g. Android12]
 - 版本号 [e.g. v0.1.0-alpha.0]

**Comment by maotoumao** [comment]
ok 我试试~

**Comment by maotoumao** [comment]
是个手机版的bug，这周的版本修复~

**Comment by showyoulove1990** [comment]
> 是个手机版的bug，这周的版本修复~

@maotoumao 大佬，还有个问题咨询下，我把移动端在车机上安装了，但是方向盘上的上下一曲按键没适配，这个能适配一下吗？
