### ISSUE TITLE
可能网络问题会导致播放歌曲的异常

### ISSUE THREAD

**Issue by wzyazkwxm** [maotoumao/MusicFree#135]
嗯，就是我开启代理工具之后，他播放异常。歌曲播放不了，自动跳过下一首。一直循环。，嗯，那个日志那里提示。播放失败自动跳过。一直有这样的日志提示。，所以估计是开启代理工具缘故导致的。这个问题我也不知道怎么解决，我就反馈一下，应该是一个小问题。

**Comment by wzyazkwxm** [comment]
系统上的异常就是一直跳来跳去的。通知栏那边。播放框界面一会有一会没的。这个应该只影响播放网络歌曲，本地的歌曲应该不会受影响。

**Comment by maotoumao** [comment]
无法播放时就会自动跳过，本地歌曲确实不受影响
