### ISSUE TITLE
Music Free ios 开发问题记录

### ISSUE THREAD

**Issue by zhuguibiao** [maotoumao/MusicFree#16]
# Music Free ios 开发问题记录

## 开发环境

按[react-native@0.69官网](https://reactnative.dev/docs/0.69/environment-setup)搭建ios开发环境

我这边的开发环境：  
- 代码库版本：2022.10.30 v0.0.1-alpha.7
- react-native-cli: 2.0.1
- react-native: 0.69.6
- yarn: 1.22.19
- ruby: 2.7.5
- cocoapods: 1.11.3
- node: 16.17.0
- xcode: 14

开始
``` bash
yarn install
cd ios && pod install
npx react-native start

# simulator 是你ios的模拟器版本
npx react-native run-ios --simulator='iPhone 14 Pro'

```

## 样式问题
1. textAlignVertical: 'center'只支持安卓，不支持ios，需要用lineHeight替代
2. 运行到模拟器的时候，可能会出现icon找不到，[参考react-native-vector-icons](https://github.com/oblador/react-native-vector-icons#ios )

## ios卡片切换背景
由于ios默认卡片动画，在切换下一个card的过程中会显示前一个card，使得滑动看起来很奇怪

![卡片切换问题](https://img-blog.csdnimg.cn/d21af0798f494e72a3c220299693f83a.jpeg)

解决思路：
   1. 每个路由页面里面添加背景色或图片
   2. 使用[react-navigation/native](https://reactnavigation.org/docs/stack-navigator)，自定义你想要的切换动画

## 播放问题
问题及解决方案：
   1. 在src/core/musicQueue.ts 399行
   
        ```js
        await TrackPlayer.add([track, getFakeNextTrack()]);
        // getFakeNextTrack 方法返回值
        if (track) {
            return produce(track, _ => {
                _.url = '';
            });
        } else {
            return { url: ''};
        }
        ```
 - 调用TrackPlayer.add方法，ios版本url必须有值，不能为空，所以播放失败，可以使用
      
    ```js
    if (!!LocalMusicSheet.isLocalMusic(track) && !track.url) {
        // 本地音乐url 处理
        return produce(track, _ => {
             _.url = _?.$?.localPath || '';
            // 自动下一首歌标记
            _.nextPalySign = 1;
        });
    }
    // 其他音频url
    return produce(track, _ => {
        _.nextPalySign = 1;
    });
    // 104行的事件里面判断改成
    !(await TrackPlayer.getTrack(evt.nextTrack))?.nextPalySign
    ```

2. ios后台播放需要自己开启支持[react-native-track-player](https://react-native-track-player.js.org/docs/basics/background-mode)

## 文件权限
- 由于**react-native-documente-picker**选择的外部文件，只能在当前app的生命周期使用，重新打开的时候没有

- 引用 **UIDocumentPickerViewController** [apple开发文档](https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories) 里面的话在 iOS13 中，用户可以使用. 文档选择器返回目录的安全范围 URL，允许您的应用访问其容器外的内容。在这种情况下，URL 允许您的应用程序递归地访问目录及其所有内容，包括访问您将来添加到目录中的任何新项目。你的应用甚至可以**为这个 URL 保存一个书签，让它在下次启动时访问该目录**。
  
解决思路： 
1. 因为自己使用（就是懒），我是把需要导入的音乐文件放到app文件夹内就可以访问
2. [添加书签方案](https://wanahue.cn/index.php/2021/05/08/uidocumentpickerviewcontroller-%E7%94%A8%E6%B3%95/)
3. 虽然文件看不到，但是react-native-track-player可以播放，可以从媒体路径这方面下手
4. 等@maotoumao 开发，哈哈~~~

## 后续
后续可以跟着@maotoumao  大佬主版本开发，完~

**Comment by maotoumao** [comment]
感谢分享ios打包经验~~~ ☺

**Comment by yong-s** [comment]
期待大佬把iOS做大做强

**Comment by hoochanlon** [comment]
现在各家平台的版权保护真鸡巴严，会不会引起版权问题的警告啊，有点担心.jpg

**Comment by wencyGit** [comment]
看了源码，一时没看懂歌词滚动到对应歌词的逻辑，能否指明一下呢😅
@maotoumao

**Comment by zhuguibiao** [comment]
> 看了源码，一时没看懂歌词滚动到对应歌词的逻辑，能否指明一下呢😅 @maotoumao

歌词一般格式是时间加歌词，比如：**[00:06.00]爱我还是他**，歌曲播放到这个6s这个时间点，匹配到对应时间歌词position，然后滚过去啦～

**Comment by maotoumao** [comment]
@wencyGit 

@zhuguibiao 说的没错～ 主要是在这里（src/pages/musicDetail/components/content/lyric.tsx）：

![image](https://github.com/maotoumao/MusicFree/assets/31655147/a75e4a29-5157-45d8-966b-b7954e9923a2)

当lyric变动的时候，通过列表的scrollToIndex滚动到对应index的歌词项；

有些地方写的不是很好😂，有啥觉得不合逻辑的提issue就行

**Comment by qiupo** [comment]
不关心ui问题，打包出来还是能用的，改成ipa自签一下就能用
[musicFree.zip](https://github.com/maotoumao/MusicFree/files/13112563/musicFree.zip)

**Comment by sgr997** [comment]
> 不关心ui问题，打包出来还是能用的，改成ipa自签一下就能用
> 
> [musicFree.zip](https://github.com/maotoumao/MusicFree/files/13112563/musicFree.zip)
> 
> 
感谢，确实可以安装使用，不过bilibili搜出来播放经常出错，不太稳定，偶尔可以播放成功，也有错误日志![image](https://github.com/maotoumao/MusicFree/assets/51942582/065900ed-43bc-4cee-b0a0-364403c5d576)

**Comment by yong-s** [comment]
> 不关心ui问题，打包出来还是能用的，改成ipa自签一下就能用 [musicFree.zip](https://github.com/maotoumao/MusicFree/files/13112563/musicFree.zip)

谢谢大佬，已经自签成功了🙏

**Comment by bosschen123** [comment]
什么时候能开发TV版

**Comment by simulationddln** [comment]
对了，安装不了是不是要巨魔或者test flight呀，有没有人给我test flight邀请码下musicfree呀？

**Comment by GarraWong** [comment]
xcode : Version 15.4 
ExpoModulesProvider 会报错 No such module 'ExpoModulesCore'
[同样的问题](https://github.com/expo/expo/issues/17511)

**Comment by osinn** [comment]
- 拉取代码启动报错 Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac FAILED
- jdk是什么版本呢？现在用的开发环境都是哪些版本呢

**Comment by wencyGit** [comment]
- 拉取最新代码运行启动
- 控制台提示 Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: src/entry/router.tsx -> src/pages/history/index.tsx -> src/entry/router.tsx 
- app上也提示
@maotoumao

**Comment by wencyGit** [comment]
- 拉去0.4.3版本的代码，报错如下

```
node:stream could not be found within the project or in these directories:
  node_modules
  ../../../../node_modules
  49 | const undici = __importStar(require("undici"));
  50 | const whatwg_mimetype_1 = __importDefault(require("whatwg-mimetype"));
> 51 | const node_stream_1 = require("node:stream");
     |                                ^
  52 | const options_js_1 = require("./options.js");
  53 | const load_parse_js_1 = require("./load-parse.js");
  54 | /**
```
- 删除node_modules，重新安装依赖，运行这么会报这么问题呢？怎么解决？

**Comment by wencyGit** [comment]
建议showPanel显示搜索歌词面板新增一个参数，用于选择后是否关联歌词，例如有些场景只是想借助这个搜索面板搜索出歌曲信息，选择歌曲后并不想关联歌曲，单纯只是想拿到歌曲的信息

**Comment by osinn** [comment]
![image](https://github.com/user-attachments/assets/eb9a931d-d4f5-4a85-81a9-c0cd32833313)

- 请教个问题，为什么这里的初始化实例为 undefined 呢？怎样修改才能正确初始化实例呢

**Comment by joyearzheng** [comment]
就收到一条错误信息，不知道什么意思：
MusicFree 错误报告
版本 1.0.0-beta.1 (400011) · android 16 · V2458A
设备标识 40ae5f2e-3792-4404-a889-28add80762a9
时间 2026-09-07T09:09:40.429Z
页面 HomeContent
来源 未捕获异常 · 发生 2 次

AxiosError: Request failed with status code 503

--- 调用栈（请保持原样，改动会导致无法定位）---
AxiosError: Request failed with status code 503
    at construct (native)
    at apply (native)
    at _construct (address at index.android.bundle:1:1102670)
    at Wrapper (address at index.android.bundle:1:3404281)
    at construct (native)
    at _callSuper (address at index.android.bundle:1:1101679)
    at AxiosError (address at index.android.bundle:1:2814508)
    at onloadend (address at index.android.bundle:1:3618461)
    at invoke (address at index.android.bundle:1:1157402)
    at dispatch (address at index.android.bundle:1:1156739)
    at value (address at index.android.bundle:1:2415878)
    at dispatchTrustedEvent (address at index.android.bundle:1:1155735)
    at setReadyState (address at index.android.bundle:1:2449278)
    at __didCompleteResponse (address at index.android.bundle:1:2447415)
    at apply (native)
    at anonymous (address at index.android.bundle:1:3407551)
    at apply (native)
    at emit (address at index.android.bundle:1:2401684)
    at apply (native)
    at anonymous (address at index.android.bundle:1:2401140)
    at emit (address at index.android.bundle:1:2401082)
    at ?anon_0_ (address at index.android.bundle:1:3861358)
    at throw (native)
    at asyncGeneratorStep (address at index.android.bundle:1:1308949)
    at _throw (address at index.android.bundle:1:3791905)
    at tryCallOne (address at InternalBytecode.js:1:1296)
    at anonymous (address at InternalBytecode.js:1:4984)

--- 已启用插件 ---
歌词网 0.0.0
👖裤佬SVIP音源 8.8.8
Audiomack 0.0.2
Navidrome 0.0.0
歌词千寻 0.0.0
猫耳FM 0.1.4
suno 0.0.0
快手 0.0.2
Youtube 0.0.1
音悦台 0.0.1
WebDAV 0.0.2
网易云电台 0.0.2
千千 0.1.3
元力KG 0.1.0
元力WY 0.1
元力KW 0.1.0
元力QQ 0.1.0
元力MG 0.1.0
酷我(念心音源) 1.0.0
弥音QQ(128k) 1
maflya.com音源 8.8.8
果核音乐 0.0.1
网易音乐 2025.09.14
爱听 0.1.0
bilibili 0.3.0
酷狗 0.1.3
小秋音乐 0.3.0
小蜜音乐 0.3.0
小蜗音乐 0.3.0
小枸音乐 0.3.0
小芸音乐 0.3.0
