### ISSUE TITLE
[FEATURE]  图标太丑，换一个

### ISSUE THREAD

**Issue by lmpker** [maotoumao/MusicFree#166]
**注意事项**
- [x] 确保已经阅读过ReadMe并*了解本软件的定位*
- [x] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**

图标太丑

**替代方案**

换一个

**其他信息**
1. 没用国内的图床，猫猫应该能看到。
2. 我用的PC版，图标就一个白块，丑死了。
3. AI生成了三个图标，2个深色，1个浅色，入得了法眼的话用一个，或者抽时间生成一个。

![Music Free1](https://github.com/maotoumao/MusicFree/assets/9392663/68b414c8-9fdc-4bfb-9937-0fb38f908059)
![Music Free2](https://github.com/maotoumao/MusicFree/assets/9392663/0d2d3212-0d56-4431-9a56-64c64835dc40)
![Music Free3](https://github.com/maotoumao/MusicFree/assets/9392663/905c3a2a-48bb-4a05-a734-2dbbf924c903)

**Comment by Petricho0r** [comment]
pc 端可以自定义图标的，可以自己换的

**Comment by zong86** [comment]
> pc 端可以自定义图标的，可以自己换的

怎么弄
