### ISSUE TITLE
安卓13不兼容，无法获取存储权限

### ISSUE THREAD

**Issue by whywwd85** [maotoumao/MusicFree#18]
只有导入本地音乐选择文件夹时可以临时受权，失去焦点就会消失。也无法主动受权给APP。

**Comment by maotoumao** [comment]
这里做了些修改，正在测试了，大概周末更新～
不过我没有安卓13的手机，如果方便的话可以帮忙测试一下吗～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月11日 11:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 安卓13不兼容，无法获取存储权限 (Issue #18) |

只有导入本地音乐选择文件夹时可以临时受权，失去焦点就会消失。也无法主动受权给APP。

**Comment by maotoumao** [comment]
下个版本修复~

**Comment by whywwd85** [comment]
感谢回复！我也希望能够帮忙测试。
前天在邮件里回复的，今天到这里才发现邮件回复的您可能收不到。为了反馈才注册的账号，英文界面不太会操作。

**Comment by whywwd85** [comment]
感谢回复！我也很高兴能帮忙测试。
前天在邮件里回复的，今天到这里才发现邮件回复的您可能收不到。为了反馈才注册的账号，英文界面不太会操作。

**Comment by maotoumao** [comment]
没关系~ 可以邮件lhx_xjtu+163.com (+换成@) 我会收到通知的~
