### ISSUE TITLE
[BUG] 歌單及我喜歡的歌單裡歌曲太多(大於1萬首歌)時，歌單內的歌會莫名地消失！

### ISSUE THREAD

**Issue by Oscor** [maotoumao/MusicFree#183]
**注意事项**
- [x] 确保该bug可能是软件的本身问题，不是由于插件导致（如搜索结果不全，无法导入等都属于插件问题）；如果是插件问题请去对应第三方插件仓库提issue。
- [x] 确保已经搜索过issue区，并阅读过QA

**详细的复现步骤**
按步骤详细描述一下触发bug的特定行为：
1：建立一個新歌單
2：將其它的歌單內的歌加入該歌單
3：當大於1萬首時，軟件重開時該歌單內的歌會消失
4：建議直接建立一歌單，裡面連結其它歌單及專輯和收藏的歌單

**其他信息:**
 ![Screenshot_20240209_205028.jpg](https://github.com/maotoumao/MusicFree/assets/21992730/438be097-9d7d-4d4e-bb1b-d21119074d02)

**Comment by maotoumao** [comment]
新年好~ 抱歉没有及时回复。

是一次性加入>1万首歌曲嘛？大概是因为目前使用的离线存储 [react-native-async-storage](https://react-native-async-storage.github.io/async-storage/docs/limits) 限制了最大存储 6MB，虽然我调整到了 20 MB 但还是可能会超过限制；超过限制后表现会变成类似：当次添加成功，但重启后歌曲消失。

![image](https://github.com/maotoumao/MusicFree/assets/31655147/f397b64c-3f68-4f19-95fc-2ad6c184169d)

目前看来最好的办法应该是改成数据库存储，不过这一部分还在实验中~~

**Comment by maotoumao** [comment]
新版本已修复
