### ISSUE TITLE
[BUG] package-lock.json 错误

### ISSUE THREAD

**Issue by lovegaoshi** [maotoumao/MusicFree#191]
**注意事项**
- [ ] 确保该bug可能是软件的本身问题，不是由于插件导致（如搜索结果不全，无法导入等都属于插件问题）；如果是插件问题请去对应第三方插件仓库提issue。
- [ ] 确保已经搜索过issue区，并阅读过QA

---

**问题描述**
package-lock.json 里面有merge conflict字段，没法用 npm i / npm ci

**详细的复现步骤**
package-lock.json

**预期行为**
更新package-lock.json

**截图**
附带一些截图/录屏吧，如果方便的话打开侧边栏-基本设置-记录详细日志，复现之后贴一下Android/data/fun.upup.musicfree/files/log/trace-log.log下的日志（完成之后记得删掉，不然时间长了会卡）

**其他信息:**
 - OS: [e.g. Android12]
 - 版本号 [e.g. v0.1.0-alpha.0]

**Comment by maotoumao** [comment]
确实。。。一直没注意。。。😥
