### ISSUE TITLE
[FEATURE] 添加插件管理中安装插件可以选择文件夹安装功能

### ISSUE THREAD

**Issue by ACodeHX** [maotoumao/MusicFree#195]
**注意事项**
- [ ] 确保已经阅读过ReadMe并*了解本软件的定位*
- [ ] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
请详细描述一下需求场景，以及可能导致的问题；以及你预期的解决方案或效果

`在本地安装插件时，只能选择一个插件安装，如果有多个插件，那么安装就麻烦一点，添加选择文件夹安装更好解决这个问题`

**替代方案**
如果无法实现，请描述一下预期的替代方案或最低期望

**其他信息**
是否能提供一些其他的帮助，包括但不限于代码、UI、测试 ... 如果有的话，辛苦描述一下，感谢~

**Comment by maotoumao** [comment]
本地文件是可以选多项的呀
![611ebf2b0f1b187863be42337126262](https://github.com/maotoumao/MusicFree/assets/31655147/da5e2261-32d3-478b-95d9-2f23f6960033)
