### ISSUE TITLE
BYD车机横屏状态下显示异常

### ISSUE THREAD

**Issue by liub1934** [maotoumao/MusicFree#2]
宽屏模式显示有问题，页面无法滑动
![1af413f4ef1efe999cf30056831977f](https://user-images.githubusercontent.com/29849550/194747041-9e4c3c7d-723b-4922-886e-aa13fdb28f2b.jpg)

我的歌单点击+号后
![74739fefab79cdf312f9669ff816496](https://user-images.githubusercontent.com/29849550/194747054-20bf3370-378d-4409-b5f3-171106bf46d9.jpg)

**Comment by maotoumao** [comment]
横屏暂时还没做适配~ 等基本功能完成后我想想怎么改一下~

**Comment by tyuan511** [comment]
想装车机上+1
