### ISSUE TITLE
[FEATURE] 下载的音乐文件名过长且冗余

### ISSUE THREAD

**Issue by hunyanjie** [maotoumao/MusicFree#203]
希望增加一个选项，支持用户自定义是否显示下载来源的内容，并且支持用户自定义分隔符，比如把@换成-。
![Screenshot_2024-04-06-17-15-08-57_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/maotoumao/MusicFree/assets/67376760/6dbaeda5-7d46-4aa7-8bc4-39417e373747)

**Comment by maotoumao** [comment]
因为目前没写入mp3 tag，所以暂时不支持修改
