### ISSUE TITLE
[FEATURE] iCON 推荐

### ISSUE THREAD

**Issue by xiyionxiong** [maotoumao/MusicFree#205]
![_f904c9a7-ad86-4d60-8668-d3a04cba0b07](https://github.com/maotoumao/MusicFree/assets/14977994/837d6111-995a-41cf-994f-c26ecdd2adc4)
![_fbe30a65-a819-4896-b5e5-35bb96002ba9](https://github.com/maotoumao/MusicFree/assets/14977994/a64d193c-1c85-4dcd-a957-a819427d5c6e)

**Comment by dong8yong8** [comment]
现在的图标确实有点丑
