### ISSUE TITLE
以后会支持鸿蒙原生吗

### ISSUE THREAD

**Issue by dong8yong8** [maotoumao/MusicFree#212]
鸿蒙后边不支持apk了, 会支持鸿蒙原生么

**Comment by maotoumao** [comment]
初步看了下 鸿蒙不支持 `new Function` 和 `eval`，所以无法直接支持插件的逻辑；

解决方案可能会是再嵌入一个js解释器之类的… 等到真的不支持apk的那天再考虑支持鸿蒙原生吧 😄

**Comment by heiwa9** [comment]
Next 已经发布了，希望可以发布 .hap 包

**Comment by heiwa9** [comment]
如果有需要的话，我可以测试 平板端
