### ISSUE TITLE
B站插件什么都搜索不出来

### ISSUE THREAD

**Issue by LvShuaiChao** [maotoumao/MusicFree#22]
![image](https://user-images.githubusercontent.com/35528109/203690016-a3db42b9-e2e4-411e-8bfe-2c41dd42f26d.png)
![image](https://user-images.githubusercontent.com/35528109/203690053-4bb14fbe-94f1-4c0a-b42c-103a2361c907.png)
B站插件什么都搜索不出来，而其他平台的插件则工作正常

**Comment by maotoumao** [comment]
示例插件里B站结果都在专辑里哈
