### ISSUE TITLE
 webdav使用教程和疑惑

### ISSUE THREAD

**Issue by specked2527** [maotoumao/MusicFree#220]
插件管理-从网络安装-https://gitee.com/maotoumao/MusicFreePlugins/raw/master/plugins.json

参考
![Screenshot_20240512194609](https://github.com/maotoumao/MusicFree/assets/124735279/5c7d2a8c-de71-4dda-9552-22548653ad96)

搜索你要的歌曲
![Screenshot_20240512194935](https://github.com/maotoumao/MusicFree/assets/124735279/6a077054-cff2-45f4-9e36-d8b1d3fe0bc2)

疑惑
我找了半天才发现没有webdav文件管理♿
只能单曲搜索

**Comment by specked2527** [comment]
我不能批量添加到歌单

**Comment by maotoumao** [comment]
是的… webdav插件写的不好，只做了搜索...

**Comment by specked2527** [comment]
> 是的… webdav插件写的不好，只做了搜索...

等等，我搞错了
webdav是可以批量添加歌单和删除的
![Screenshot_20240512231706](https://github.com/maotoumao/MusicFree/assets/124735279/79dc0eff-624e-4877-ac97-d9452841e18f)
管理操作怎么在-榜单-这个按钮里？
超级诡异，真的找不到

**Comment by xtccc** [comment]
我测试是使用英文逗号分割不同的目录，然后重启app生效。

ps: 我研究了好一会儿，直到看了眼插件的流程才发现插件初始化是在启动app的时候
