### ISSUE TITLE
[FEATURE] Publish on F-Droid

### ISSUE THREAD

**Issue by linsui** [maotoumao/MusicFree#243]
**注意事项**
- [x] 确保已经阅读过ReadMe并*了解本软件的定位*
- [x] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
可以打包应用在 F-Droid 发布吗？我可以帮助打包，但需要你的同意。

**替代方案**
如果无法实现，请描述一下预期的替代方案或最低期望

**其他信息**
是否能提供一些其他的帮助，包括但不限于代码、UI、测试 ... 如果有的话，辛苦描述一下，感谢~

**Comment by maotoumao** [comment]
抱歉回晚了… 问下发布到F-Droid需要准备什么呢？
而且目前打包的密钥是存在我本地的 :)

**Comment by linsui** [comment]
发布到 F-Droid 需要提交一个 metadata 用于构建 apk。这个我可以做，目前的问题在于 readme 中的禁止商用条款附加在 GPL 上构成的协议不再是开源协议，不符合 F-Droid 的要求。请问是否可以去掉此条款？目前看来它也没有起到作用。

F-Droid 分发的应用一般由 F-Droid 签名，如果采用可重复构建的方式则使用开发者的签名，但不需要开发者的密钥。

**Comment by maotoumao** [comment]
明白了，我仔细看了下F-Droid的说明，确实有这方面的限制。
不过，readme中声明的禁止商用的条款没有打算去掉，所以先不考虑发布到F-Droid了 :) 谢谢

**Comment by linsui** [comment]
好的，理解 :ok_hand:
