### ISSUE TITLE
[BUG] 歌词翻译错位

### ISSUE THREAD

**Issue by ProjectNyaser** [maotoumao/MusicFree#245]
### Discussed in https://github.com/maotoumao/MusicFree/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **ProjectNyaser** May 21, 2024</sup>
![Screenshot_2024-05-21-23-27-12-523_fun.upup.musicfree.jpg](https://github.com/maotoumao/MusicFree/assets/61904116/e0b59c15-bce0-43e4-8072-db2d426159f3)

如图所示，翻译向下移两句就正常了，_似乎有翻译的歌曲都会这样_。</div>

**Comment by maotoumao** [comment]
已经修复了
