### ISSUE TITLE
[FEATURE] 封面自动跳转歌词

### ISSUE THREAD

**Issue by yuanzl77** [maotoumao/MusicFree#247]
**你好！我想提出点意见，尊敬的开发者可以看看是否合理。**
在设置中加个 **展示封面跳转歌词** 默认3秒 3秒过后自动跳转歌词。我知道可以选默认展示封面还是歌词，你们看看这个想法怎么样呢？
**ui有点丑，采用md3试试看?**
好的，这些就是我的想法，**谢谢! 辛苦!**

**Comment by maotoumao** [comment]
谢谢，UI风格持续优化中
