### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by Apocalypse-QWQ** [maotoumao/MusicFree#25]
系统A12，MIUI13，app版本alpha10，网易云插件版本0.0.6
在上述环境下导入网易云歌单”我喜欢的音乐“时必然失败，其他的任意歌单均成功导入，可排除本地网络环境原因，希望开发者尽快修复，谢谢。

**Comment by maotoumao** [comment]
网易云默认歌单暂时导不了 先新建一个歌单把默认歌单复制一下再导入吧~
