### ISSUE TITLE
[BUG] mac m1 版无法使用

### ISSUE THREAD

**Issue by Charlo-O** [maotoumao/MusicFree#250]
<img width="258" alt="image" src="https://github.com/maotoumao/MusicFree/assets/49369951/ed458eac-9ced-4c5b-ae62-5ce22fc6d543">
使用arm版显示已损坏，用x86显示这个，是我的电脑问题还是软件问题呀

**Comment by Gtanghaibo** [comment]
遇到了同样的问题

**Comment by aoping** [comment]
+1
