### ISSUE TITLE
喜欢歌曲排在最下方，能否改为最上方？

### ISSUE THREAD

**Issue by momo6351** [maotoumao/MusicFree#256]

**Comment by Hopelsz** [comment]
看看这里是不是你想要的效果？
![Screenshot_2024-07-29-23-04-07-503_fun upup musicfree-edit](https://github.com/user-attachments/assets/c6bf29ac-fa8c-40b9-8a44-213ab55ae05f)

**Comment by momo6351** [comment]
是的是的，没研究明白 感谢
