### ISSUE TITLE
许可协议本身冲突

### ISSUE THREAD

**Issue by yjacks** [maotoumao/MusicFree#262]
GPL3.0保留了二次分发时收费的权利，并且允许将代码用作商业使用。
麻烦作者再次、明确地声明：本作品是完全适用于GPL3.0，还是另外附加特例。
万分感谢作者，感谢您在这个项目上花费了无数心血。

**Comment by maotoumao** [comment]
谢谢指出~ 仔细看了下GPL协议确实是这样，并且貌似在GPL协议上附加的条款都是无效的
我找时间再研究一下~~~ 谢谢~~

**Comment by maotoumao** [comment]
切换成了AGPL协议~ 谢谢指出~

**Comment by yhx0022** [comment]
> 切换成了AGPL协议~ 谢谢指出~

能把musicfree上架到f-droid应用商店吗？
