### ISSUE TITLE
能在插件中增加推荐歌单吗？

### ISSUE THREAD

**Issue by lhjgege** [maotoumao/MusicFree#27]
如题，能不能在插件中增加推荐歌单功能，有什么不知道听啥只想去推荐歌单里面听。但是没有推荐歌单

**Comment by maotoumao** [comment]
在考虑了～ 这周去做了点别的事情，下周开始更～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月17日 22:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 能在插件中增加推荐歌单吗？ (Issue #27) |

如题，能不能在插件中增加推荐歌单功能，有什么不知道听啥只想去推荐歌单里面听。但是没有推荐歌单

**Comment by MarxLee55** [comment]
能否增加个性化推荐呢，按照用户喜欢的音乐风格推荐类似的音乐
