### ISSUE TITLE
[BUG] 手机端webdav 搜不到文件

### ISSUE THREAD

**Issue by oldsento** [maotoumao/MusicFree#272]
**注意事项**
- [ ] 确保该bug可能是软件的本身问题，不是由于插件导致（如搜索结果不全，无法导入等都属于插件问题）；如果是插件问题请去对应第三方插件仓库提issue。
- [ ] 确保已经搜索过issue区，并阅读过QA

---
想添加坚～果的webdav 访问但搜索不到文件，是文件夹路径的问题吗？备份同步数据是没问题

**其他信息:**
 - OS: [e.g. Android10]
 - 版本号 [ v0.3.0]

**Comment by oldsento** [comment]
其他支持访问的软件都可以正常添加，

**Comment by oldsento** [comment]
话说5sing插件可以搜索但放不了歌，版本0.1.1，是不是该更新了啊

**Comment by FFlowerS** [comment]
目前看到的是，如果音乐文件在根目录下就可以搜索到，如果是套娃目录就不行

----

<img width="908" alt="Snipaste_2024-08-31_17-56-17" src="https://github.com/user-attachments/assets/0fbba0b3-c673-4cd4-bfde-3499e5cdda56">
<img width="827" alt="Snipaste_2024-08-31_17-55-29" src="https://github.com/user-attachments/assets/95513694-e29a-4132-92a5-d069204f74ba">

**Comment by oldsento** [comment]
> PC端和手机端都测试了一下，目前看到的是，如果音乐文件在根目录下就可以搜索到，如果是套娃目录就不行：
> 
> ----
> 
> <img width="908" alt="Snipaste_2024-08-31_17-56-17" src="https://github.com/user-attachments/assets/0fbba0b3-c673-4cd4-bfde-3499e5cdda56">
> <img width="827" alt="Snipaste_2024-08-31_17-55-29" src="https://github.com/user-attachments/assets/95513694-e29a-4132-92a5-d069204f74ba">
> <img width="720" alt="Snipaste_2024-08-31_17-59-42" src="https://github.com/user-attachments/assets/712f144f-d52f-4cf4-8f5c-cecb0c86a763">
> 
> 
> 
> ----
> 
> 音乐格式到是都能支持

![Screenshot_2024_0901_163146.png](https://github.com/user-attachments/assets/ce0f61cd-3962-4f53-aa93-2de5293ae39c)
还是不行啊，是哪里的问题，还是软件版本的问题，目前窝是用0.3.0

**Comment by FFlowerS** [comment]
> > PC端和手机端都测试了一下，目前看到的是，如果音乐文件在根目录下就可以搜索到，如果是套娃目录就不行：
> > 
> > <img alt="Snipaste_2024-08-31_17-56-17" width="908" src="https://private-user-images.githubusercontent.com/8475161/363404301-0fbba0b3-c673-4cd4-bfde-3499e5cdda56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODAwMzIsIm5iZiI6MTcyNTE3OTczMiwicGF0aCI6Ii84NDc1MTYxLzM2MzQwNDMwMS0wZmJiYTBiMy1jNjczLTRjZDQtYmZkZS0zNDk5ZTVjZGRhNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMDgzNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzEzODNmN2M3NTEyYzdmMjk1ZTY3ZTE3MDJhMDc2MmRjMmQ2ODRmY2Y0NThiOTc3NjYzNjA4YmE0ZjhlN2M0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RfMMvfDi1Tw8m5F_5o8M-pzMzaFSe1SeAISuSgnYPuo">
> > <img alt="Snipaste_2024-08-31_17-55-29" width="827" src="https://private-user-images.githubusercontent.com/8475161/363404304-95513694-e29a-4132-92a5-d069204f74ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODAwMzIsIm5iZiI6MTcyNTE3OTczMiwicGF0aCI6Ii84NDc1MTYxLzM2MzQwNDMwNC05NTUxMzY5NC1lMjlhLTQxMzItOTJhNS1kMDY5MjA0Zjc0YmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMDgzNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg5NTQ0NGIwNmMxODUzM2IwODBmN2NiMTkzNTQ2NzE1NWUxYTYyM2Y5MzIxOWY2MjczMmViZjMyNjAwZGIzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.33UJOExWQMsA9-RUHoYclOiKwG_9CwGVMFzcnJ9HeEc">
> > <img alt="Snipaste_2024-08-31_17-59-42" width="720" src="https://private-user-images.githubusercontent.com/8475161/363404505-712f144f-d52f-4cf4-8f5c-cecb0c86a763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODAwMzIsIm5iZiI6MTcyNTE3OTczMiwicGF0aCI6Ii84NDc1MTYxLzM2MzQwNDUwNS03MTJmMTQ0Zi1kNTJmLTRjZjQtOGY1Yy1jZWNiMGM4NmE3NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMDgzNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFiN2IyNjBhNjNhMmI4YmFiNzBmZTY3NjY5YjAyYmEzOGU0MDQ0ZjI3NjlhMWUxMjRkODU0OTlkNWRlNmJmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LSRm74f7WnXVwa_qOYpWpsqTXL8VqMUF8jEVpgub2QQ">
> > 
> > 音乐格式到是都能支持
> 
> ![Screenshot_2024_0901_163146.png](https://private-user-images.githubusercontent.com/169301064/363476832-ce0f61cd-3962-4f53-aa93-2de5293ae39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODAwMzIsIm5iZiI6MTcyNTE3OTczMiwicGF0aCI6Ii8xNjkzMDEwNjQvMzYzNDc2ODMyLWNlMGY2MWNkLTM5NjItNGY1My1hYTkzLTJkZTUyOTNhZTM5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwODM1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWFkN2VhNzNiNTc1MjdlZWE0ZjA2ZGIwZDM0MTdkZThkOGExMGJlMzZiZmM3ZjM0Yjg3MTRlODRiODI3YTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jm05FcVNM8owIpG_4i-qWXJ6Ti515NwcNQz7R45VZzQ) 还是不行啊，是哪里的问题，还是软件版本的问题，目前窝是用0.3.0，话说你确实可以播放吗？

播放倒是能播放；还是等着开发者看看吧，我也就是试试

**Comment by oldsento** [comment]
刚刚测试了，原来是文件夹路径真的有问题，把前面的adv删除了就可以了，

话说发现一个问题，m4a不支持显示但我把后缀名改成mp3 就显示了

**Comment by emf1002** [comment]
> 刚刚测试了，原来是文件夹路径真的有问题，把前面的adv删除了就可以了，
> 
> 话说发现一个问题，m4a不支持显示但我把后缀名改成mp3 就显示了


我是用alist搭建的webdav，怎么配置歌曲都出不来，也没有错误提示，能把正确的配置贴出来看看吗？

**Comment by oldsento** [comment]
> > 刚刚测试了，原来是文件夹路径真的有问题，把前面的adv删除了就可以了，
> > 
> > 话说发现一个问题，m4a不支持显示但我把后缀名改成mp3 就显示了
> 
> 
> 我是用alist搭建的webdav，怎么配置歌曲都出不来，也没有错误提示，能把正确的配置贴出来看看吗？

已经支持alist了？从哪个版本开始的，窝很久没更新了
