### ISSUE TITLE
更新0.40后无法开启桌面歌词

### ISSUE THREAD

**Issue by gaotianliuyun** [maotoumao/MusicFree#286]
如题，系统提示打开手机系统。![Screenshot_2024-09-07-06-59-28-250_fun.upup.musicfree.jpg](https://github.com/user-attachments/assets/3cdae4e3-c315-49af-9218-fe1644309599)

**Comment by maotoumao** [comment]
是个bug 会尽快修

**Comment by maotoumao** [comment]
fixed
