### ISSUE TITLE
[BUG] 只要调整了桌面歌词背景色，桌面歌词开关就无法打开了

### ISSUE THREAD

**Issue by ghsqhub** [maotoumao/MusicFree#288]
![Screenshot_2024-09-07-21-43-08-123_fun.upup.musicfree-edit.jpg](https://github.com/user-attachments/assets/8d64a335-e36b-4c0e-adbf-9036844ad98c)

只能卸载重装才行

**Comment by maotoumao** [comment]
是个bug 会尽快修
