### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by lzb-libra** [maotoumao/MusicFree#29]
1、希望增加个一个其他app歌单导入的功能
2、希望增加一个云盘备份歌单的功能
3、希望适配ipad之类的大屏设备
4、希望适配一下华为手机负一屏那个音乐软件识别的问题，现在在华为手机负一屏上不能识别咱们的播放软件

**Comment by maotoumao** [comment]
导入歌单其实已经有了 只不过插件没有适配

后边三个都有计划，只不过可能会比较久～～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月26日 09:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 功能建议 (Issue #29) |

1、希望增加个一个其他app歌单导入的功能
2、希望增加一个云盘备份歌单的功能
3、希望适配ipad之类的大屏设备
4、希望适配一下华为手机负一屏那个音乐软件识别的问题，现在在华为手机负一屏上不能识别咱们的播放软件

**Comment by gaigai12** [comment]
希望加入听书网站的源我这有几个js 不会改成你这个软件规则 你有空看看{"key":"drpy_js_海盗听书","name":"听书 | 海盗听书","type":3,"api":"https://gitcode.net/qq_32394351/dr_py/-/raw/master/libs/drpy2.min.js","ext":"https://gitcode.net/qq_32394351/dr_py/-/raw/master/js/海盗听书.js","playerType":"2"},
{"key":"drpy_js_听书网","name":"听书 | 听书网","type":3,"api":"https://gitcode.net/qq_32394351/dr_py/-/raw/master/libs/drpy2.min.js","ext":"https://gitcode.net/qq_32394351/dr_py/-/raw/master/js/听书网.js","playerType":"2"},
{"key":"drpy_js_有声小说","name":"听书 | 有声小说","type":3,"api":"https://gitcode.net/qq_32394351/dr_py/-/raw/master/libs/drpy2.min.js","ext":"https://gitcode.net/qq_32394351/dr_py/-/raw/master/js/有声小说吧.js","playerType":"2"},

**Comment by lzb-libra** [comment]
有没有计划适配鸿蒙next版
