### ISSUE TITLE
[BUG] 0.4.1小米14几乎不能用了

### ISSUE THREAD

**Issue by balladc** [maotoumao/MusicFree#293]
**注意事项**
- [x] 确保该bug可能是软件的本身问题，不是由于插件导致（如搜索结果不全，无法导入等都属于插件问题）；如果是插件问题请去对应第三方插件仓库提issue。
- [x] 确保已经搜索过issue区，并阅读过QA

---

**问题描述**
在正常播放场景下，进行上一首结束自动跳转下一首的操作，产生卡死无法继续播放现象，而不是正常播放

**详细的复现步骤**
就是全局只能听一首歌，然后必须杀后台重进才能听第二首

**预期行为**
需要能正常一直播放下去

**截图**

https://github.com/user-attachments/assets/dea3c2d7-cbb1-4a12-8627-b2b29a1894f4

糟糕，日志记录都记录不下来，music free文件夹都没，卸载重新安装，完全不能播放了

**其他信息:**
 - OS: [xiaomi hyperOS 1.0.42]
 - 版本号 [v0.4.1]

**Comment by aumt** [comment]
不只是小米，我这类原生也一样，不过是随机播放会这样，

**Comment by maotoumao** [comment]
是本地音乐的bug

**Comment by balladc** [comment]
> 是本地音乐的bug

蛤？什么意思？可以怎么客户端这边怎么搞吗？
我已经回滚0.3版本了


> 不只是小米，我这类原生也一样，不过是随机播放会这样，

我试过不止随机播放会这样，顺序也会

**Comment by maotoumao** [comment]
0.4.2已修复
