### ISSUE TITLE
[BUG] 小米12本地音乐不能播放

### ISSUE THREAD

**Issue by harry1943** [maotoumao/MusicFree#296]
### ⠀

- [X] 已阅读 Q&A

### ⠀

- [X] 非插件导致（如搜索结果不全，无法导入等都属于插件问题）

### ⠀

- [x] 不与其他 issue 重复

### 问题描述

无论是否安装插件 本地音乐导入后都不能播放。但是 从手机文件管理里选择用本软件播放，则可以播放。

### 预期行为

可正常播放

### 详细的复现步骤

导入本地音乐，播放

### 截图

https://github.com/user-attachments/assets/5cb6036f-c00c-441f-ada5-72a8c424981a

### 其他信息

小米手机12spro

**Comment by harry1943** [comment]
Uploading VID_20240910_130438.mp4…

**Comment by harry1943** [comment]
https://github.com/user-attachments/assets/7c143925-1566-4ed4-96a6-5d2947a15ab7

**Comment by jgchgjhbkj** [comment]
还搜不到原下载目录中的歌曲

**Comment by liuyq917** [comment]
我的也是

**Comment by wangcodehub** [comment]
一样，matepadpro平板上一样的问题

**Comment by zero-hugo** [comment]
同，我魅族21pro，也无法播放手机里存着的音乐。

**Comment by soso636** [comment]
一样，我扫描了阿里云盘本地文件夹，文件大约250mb，也播放不了，望修复

**Comment by copyhunt** [comment]
我华为mate30也一样 播放不了本地音乐

**Comment by wanwuzhishi** [comment]
> 荣耀X30也无法播放本地音乐

已修复
