### ISSUE TITLE
无法批量添加到播放列表

### ISSUE THREAD

**Issue by Ricardo-Lv** [maotoumao/MusicFree#3]
添加到播放列表，收藏到歌单只能挨个添加，有点麻烦

**Comment by maotoumao** [comment]
批量编辑在加了~ 需要些时间，到时候会在这里同步的

**Comment by maotoumao** [comment]
已经加好了~ 可以试试新版本：
https://gitee.com/maotoumao/MusicFree/releases/download/v0.0.1-alpha.6/app-release.apk

支持批量添加到歌单/下一首播放/删除/下载/长按拖拽排序
