### ISSUE TITLE
希望支持 opus 格式

### ISSUE THREAD

**Issue by czyczk** [maotoumao/MusicFree#31]
作为一个移动端的本地播放器，希望支持 o · 有损界的冉冉新星 · 全能的瑞士军刀 · 省流助手与存储救星 · pus 格式。（.m4a 容器内的 xHE-AAC 都能播放，没理由不支持 opus 呀）

v0.0.1-alpha.12 现状是不能被扫描到，本地的也不能指定它来播放。

**Comment by maotoumao** [comment]
貌似是因为我手动过滤了后缀😂我可以在下个版本把它加上 不过我也不确定能不能播放🤣（调包侠



---- 回复的原邮件 ----
| 发件人 | Zenas ***@***.***> |
| 日期 | 2022年12月30日 22:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 希望支持 opus 格式 (Issue #31) |

作为一个移动端的本地播放器，希望支持 o · 有损界的冉冉新星 · 全能的瑞士军刀 · 省流助手与存储救星 · pus 格式。（.m4a 容器内的 xHE-AAC 都能播放，没理由不支持 opus 呀）

v0.0.1-alpha.12 现状是不能被扫描到，本地的也不能指定它来播放。
