### ISSUE TITLE
[Feature] 能否增加播放记忆功能？这样重新打开app可以继续播放？

### ISSUE THREAD

**Issue by lionkk007** [maotoumao/MusicFree#320]
### ⠀

- [X] 已经阅读过ReadMe并*了解本软件的定位*

### 需求描述

能否增加播放记忆功能？这样重新打开app可以继续播放？

### 添加原因

当听书或课件，每次打开可以续听。

### 功能示例

无

**Comment by lionkk007** [comment]
播放 不是 播发

**Comment by lionkk007** [comment]
> ### ⠀
> * [x]  已经阅读过ReadMe并_了解本软件的定位_
> 
> ### 需求描述
> 能否增加播放记忆功能？这样重新打开app可以继续播放？
> 
> ### 添加原因
> 当听书或课件，每次打开可以续听。
> 
> ### 功能示例
> 无
> 
> ### 添加困难
> _No response_
> 
> ### 替代方案
> _No response_
> 
> ### 其他信息
> _No response_

**Comment by mengnankkkk** [comment]
同求添加这个功能，希望开发者可以看到
