### ISSUE TITLE
[BUG] 比亚迪车载平板（Android 10 API 29），扫描本地音乐，无法看到优盘及存储卡的内容。

### ISSUE THREAD

**Issue by lionkk007** [maotoumao/MusicFree#323]
### ⠀

- [X] 已阅读 Q&A

### ⠀

- [X] 非插件导致（如搜索结果不全，无法导入等都属于插件问题）

### ⠀

- [X] 不与其他 issue 重复

### 问题描述

扫描本地音乐

### 预期行为

![image](https://github.com/user-attachments/assets/b0e35b16-8032-4da
![QQ20241009-083543](https://github.com/user-attachments/assets/4d41b466-2b93-42da-a5ba-4c3b33108be9)
f-991e-7551be007b91)这是oplayer的扫描本地音乐的显示，可以把存储设备都显示出来。

### 详细的复现步骤

无

### 截图

![微信截图_20241009083726](https://github.com/user-attachments/assets/472ca109-ae8f-4216-be63-3dc3b7e6620b)
这是musicfree扫描音乐的截图

### 其他信息

比亚迪车机 Android 10 musicfree 0.4.2

**Comment by lionkk007** [comment]
研究了下，自己搞定了。将 \src\pages\fileSelector\index.tsx 中加了个
const mainExternalStoragePath = RNFS.ExternalStorageDirectoryPath;

const getAllExternalStoragePaths= async () => {
  try {
    // 读取 '/storage' 目录下的所有子目录
    const dirs = await RNFS.readDir('/storage');

    // 筛选出有效的目录并生成路径
    const externalDirs = dirs
      .filter((dir) => dir.isDirectory()) // 过滤出文件夹
      .map((dir) => `${dir.path}/Android/data`); //为了匹配后面的substring

    console.log('getAllExternalStoragePathsA 所有外部存储目录:', externalDirs);
    return externalDirs; // 返回字符串数组
  } catch (error) {
    console.error('读取外部存储目录失败:', error);
    return [];
  }
}
将const allExt = await getAllExternalFilesDirs(); 替换成 const allExt = await getAllExternalStoragePaths();
奇怪的是/storage/emulated这个目录进去后看不到0目录（不懂的怎么解决），强制将/storage/emulated改为/storage/emulated/0 
将就着能用了。
谢谢作者！第一次接触react-native和androidstudio，不懂的地方实在太多了，实在有点凑合解决问题的感觉。

**Comment by wencyGit** [comment]
> 研究了下，自己搞定了。将 \src\pages\fileSelector\index.tsx 中加了个 import RNFS from 'react-native-fs'; const mainExternalStoragePath = RNFS.ExternalStorageDirectoryPath;
> 
> const getAllExternalStoragePaths= async () => { try { // 读取 '/storage' 目录下的所有子目录 const dirs = await RNFS.readDir('/storage');
> 
> ```
> // 筛选出有效的目录并生成路径
> const externalDirs = dirs
>   .filter((dir) => dir.isDirectory()) // 过滤出文件夹
>   .map((dir) => `${dir.path}/Android/data`); //为了匹配后面的substring
> 
> console.log('getAllExternalStoragePathsA 所有外部存储目录:', externalDirs);
> return externalDirs; // 返回字符串数组
> ```
> 
> } catch (error) { console.error('读取外部存储目录失败:', error); return []; } } 将const allExt = await getAllExternalFilesDirs(); 替换成 const allExt = await getAllExternalStoragePaths(); 奇怪的是/storage/emulated这个目录进去后看不到0目录（不懂的怎么解决），强制将/storage/emulated改为/storage/emulated/0 将就着能用了。 谢谢作者！第一次接触react-native和androidstudio，不懂的地方实在太多了，实在有点凑合解决问题的感觉。

你的车机系统DiLink]是什么版本的呢？

**Comment by wencyGit** [comment]
> > 你的车机系统DiLink]是什么版本的呢？
> > 这个和Dlink版本应该没有关系。只是应该和操作系统（安卓）版本有关。你如果需要我可以发给你，我现在改了下，应该兼容其他版本安卓了（6以上），同时改了个播放列表显示的是文件名而不是音乐文件内的标题。

可以发给我看一下，前几天我也在车机上安装了，扫描不到SD卡

**Comment by lionkk007** [comment]
> > > 你的车机系统DiLink]是什么版本的呢？
> > > 这个和Dlink版本应该没有关系。只是应该和操作系统（安卓）版本有关。你如果需要我可以发给你，我现在改了下，应该兼容其他版本安卓了（6以上），同时改了个播放列表显示的是文件名而不是音乐文件内的标题。
> 
> 可以发给我看一下，前几天我也在车机上安装了，扫描不到SD卡。另外你在车机上安装过插件没？我离线安装插件会出现闪退，在线安装没试过

我是在线安装的插件，倒是没问题。
今晚又改了点东西，将播放列表显示文件名放在设置里了。
加我qq吧 547769671 加的时候记得给我发个邮件 547769671@qq.com 这邮箱绑定了微信，有邮件会提示。
