### ISSUE TITLE
插件不能下载音乐了

### ISSUE THREAD

**Issue by ymkfssy** [maotoumao/MusicFree#33]
最近不知道怎么，一点下载就显示下载完成，然后对应的目录里面没有歌曲。

**Comment by maotoumao** [comment]
难道是有bug😦 我找时间看一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月09日 21:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 插件不能下载音乐了 (Issue #33) |

最近不知道怎么，一点下载就显示下载完成，然后对应的目录里面没有歌曲。

**Comment by wulong-tea** [comment]
我这 QQ 音乐不能下载。

2023/1/16 下午3:40:31 | ERROR : 
{
  "desc": "下载出错",
  "message": "no protocol: /storage/emulated/0/Android/data/fun.upup.musicfree/files/download/music/QQ音乐@612446@夜莺@Yanni.mp3"
}

2023/1/16 下午3:51:07 | ERROR : 
{
  "desc": "下载出错",
  "message": "no protocol: /storage/emulated/0/Android/data/fun.upup.musicfree/files/download/music/QQ音乐@612446@夜莺@Yanni.mp3"
}
