### ISSUE TITLE
[BUG] 下载歌曲到 sd卡报权限拒绝

### ISSUE THREAD

**Issue by wencyGit** [maotoumao/MusicFree#333]
### ⠀

- [X] 已阅读 Q&A

### ⠀

- [X] 非插件导致（如搜索结果不全，无法导入等都属于插件问题）

### ⠀

- [X] 不与其他 issue 重复

### 问题描述

![image](https://github.com/user-attachments/assets/0e6f1500-42b3-4ace-a2d5-c541df5d5216)

- android 10版本 下载歌曲到 sd卡 报权限拒绝
- 报错信息[Error: ENOENT: open failed: EACCES (Permission denied), open '/storage/0AF2-321B/xxxx
- sd卡里面的歌曲是可以读取播放，就行下载到sd卡会有权限问题
- android 高版本就不会有这个问题
- 新安装应用，打开应用有提示授权，并授权允许

### 预期行为

- 正常可以下载到sd目录

### 详细的复现步骤

1、模拟器android api 版本为29，对应android 版本10，启动带有sd卡到模拟器
2、设置里面将下载路径改为sd卡下面的路径
3、下载歌曲就会报错[Error: ENOENT: open failed: EACCES (Permission denied), open '/storage/0AF2-321B/xxxx

### 截图

![image](https://github.com/user-attachments/assets/4a9e6b1f-0476-484d-825c-bae37ec1ac3f)

![image](https://github.com/user-attachments/assets/3827151b-4f1c-40ab-b497-a545db88db28)

### 其他信息

- 设备：模拟器、车机
- 系统版本号：Android 10
- 应用版本号：0.4.2

**Comment by maotoumao** [comment]
下载到其他文件夹有这个问题嘛？

**Comment by wencyGit** [comment]
> 下载到其他文件夹有这个问题嘛？

只要是sd卡下的都被拒绝，内部存储就没有这个问题

**Comment by wencyGit** [comment]
> 下载到其他文件夹有这个问题嘛？

- 根目录下载建的文件夹就会被拒绝，试过几个文件夹了
- 试了一下 android/data/fun.upup.musicfree目录，可以正常下载了

**Comment by wencyGit** [comment]
@maotoumao 
![image](https://github.com/user-attachments/assets/32b9d8a8-ea69-4c50-8039-1ea3b0ae1272)

- 可以在 src/pages/setting/settingTypes/basicSetting.tsx 文件中`选择文件夹`时测试是否有写入权限
