### ISSUE TITLE
华为荣耀V30Pro 鸿蒙4.2 点击添加插件 无反应，之前会弹出添加界面

### ISSUE THREAD

**Issue by BBQZZZ000** [maotoumao/MusicFree#338]
### ⠀

- [X] 已阅读 Q&A

### ⠀

- [X] 非插件导致（如搜索结果不全，无法导入等都属于插件问题）

### ⠀

- [X] 不与其他 issue 重复

### 问题描述

华为荣耀V30Pro 鸿蒙4.2 点击添加插件 无反应，之前会弹出添加界面

### 预期行为

弹出添加插件界面

### 详细的复现步骤

华为荣耀V30Pro 鸿蒙4.2 点击添加插件 无反应，之前会弹出添加界面

### 截图

https://github.com/user-attachments/assets/a88649a7-fb82-4630-8c3c-3e0a010ab2d2

### 其他信息

荣耀V30PRO
鸿蒙4.2

**Comment by wencyGit** [comment]
- 我的手机是华为荣耀V30 鸿蒙4.2，能正常使用
