### ISSUE TITLE
能否增加一个倍速播放的功能？

### ISSUE THREAD

**Issue by MMARVP** [maotoumao/MusicFree#34]
如题所述。
除了听音乐外，日常听小说和电台也很多，正常语速太慢了，希望能有倍速功能，感谢~

**Comment by maotoumao** [comment]
可以有～ 下个版本可能要到年后了 估计主要会是完善插件和补充一些小功能（最近有点忙） 我尝试下个版本加上好了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月12日 14:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 能否增加一个倍速播放的功能？ (Issue #34) |

如题所述。
除了听音乐外，日常听小说和电台也很多，正常语速太慢了，希望能有倍速功能，感谢~

**Comment by MMARVP** [comment]
感激不尽，辛苦大佬

**Comment by zhoutianling** [comment]
作者是个真汉纸，果然说话算数
