### ISSUE TITLE
[BUG]  新版本更新 勾上了不再提示，下次打开还是会提示。

### ISSUE THREAD

**Issue by l1j1al1n** [maotoumao/MusicFree#341]
### ⠀

- [X] 已阅读 Q&A

### ⠀

- [X] 非插件导致（如搜索结果不全，无法导入等都属于插件问题）

### ⠀

- [X] 不与其他 issue 重复

### 问题描述

新版本更新 勾上了不再提示，清理后台，下次打开还是会提示。

### 预期行为

想用老版本，或者新版本在设置里面检查新版本。

### 详细的复现步骤

打开MusicFree->发现新版本（0.4.3）勾选"跳过此版本"->空白处或者"取消"->清理后台->再次打开MusicFree->复现。。end。

### 截图

![43b9a8a5f723fdbb1c5f22253a1ca3e6](https://github.com/user-attachments/assets/a0a7e3a1-8b1a-4c0e-9670-3aa7e76ce85a)

### 其他信息

小米13
系统版本 hyper os 1.0.14.0.UMCCNXM
应用版本 0.4.2

**Comment by maotoumao** [comment]
是个bug.. 0.4.4修掉了 之前一直没发现..
