### ISSUE TITLE
[BUG] 恢复备份'我喜欢'歌单重复

### ISSUE THREAD

**Issue by wencyGit** [maotoumao/MusicFree#347]
### ⠀

- [X] 已阅读 Q&A

### ⠀

- [X] 非插件导致（如搜索结果不全，无法导入等都属于插件问题）

### ⠀

- [X] 不与其他 issue 重复

### 问题描述

- 备份到本地，再次从本地文件恢复
- 此时我的歌单列表中“我喜欢”歌单重复，每次恢复一次“我喜欢”歌单就会多出一个
- 这个问题不只是在 0.4.4版本出现，之前的版本也是存在的

### 预期行为

- 备份到本地，再次从本地文件恢复在我的歌单列表中“我喜欢”歌单不应该出现重复

### 详细的复现步骤

1. 备份到本地
2. 然后从本地文件恢复

### 截图

![image](https://github.com/user-attachments/assets/b18923b0-ee58-43a5-98f9-ab73a288ea8b)

### 其他信息

应用版本：0.4.4

**Comment by wellenChen** [comment]
![Uploading image.png…]()

**Comment by wellenChen** [comment]
![image](https://github.com/user-attachments/assets/20a20f5b-4e70-4d7f-bf0a-be7c0a72dcef)
