### ISSUE TITLE
问题及建议

### ISSUE THREAD

**Issue by flijun** [maotoumao/MusicFree#36]
先谢谢作者提供的好软件。两个建议或问题：
指定下载文件夹后，被指定的和原来data文件夹里都下不了，显示下载完成实际没有下载。
保存的歌单应该能导出备份，以供导入。我为了下载问题清楚app数据，只能一个个重新找回来。

**Comment by maotoumao** [comment]
下载问题下个版本可能就好了，尝试修了一下；
备份看来下个版本又来不及做了 只能再先小鸽一下了😂




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月24日 23:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 问题及建议 (Issue #36) |

先谢谢作者提供的好软件。两个建议或问题：
指定下载文件夹后，被指定的和原来data文件夹里都下不了，显示下载完成实际没有下载。
保存的歌单应该能导出备份，以供导入。我为了下载问题清楚app数据，只能一个个重新找回来。

**Comment by maotoumao** [comment]
应该都好了~
