### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by TeresaAtlas** [maotoumao/MusicFree#37]
您好，请问可以和安卓的全面屏手势做一下适配吗，每次打开软件，界面最底下有小白条，看着很难受，谢谢

![IMG_20230130_230523.jpg](https://user-images.githubusercontent.com/119603850/215515547-39de95e3-df3d-4799-a3c0-5a33b686d1c5.jpg)

**Comment by maotoumao** [comment]
附图貌似不太对，打不开~ 重新发张截图看看吧~~

**Comment by TeresaAtlas** [comment]
> 附个截图看看吧~~~

![IMG_20230130_230523.jpg](https://user-images.githubusercontent.com/119603850/215515819-2b09f10c-ab00-4600-8e7f-960bb4759317.jpg)

**Comment by TeresaAtlas** [comment]
> 附个截图看看吧~~~
截图发了

**Comment by maotoumao** [comment]
ok~ 记下了

**Comment by maotoumao** [comment]
下个版本再修... 最近在整别的😂
