### ISSUE TITLE
[FEATURE] 在win11的安卓子系统下使用，APP分辨率不能自适应的问题

### ISSUE THREAD

**Issue by milozen** [maotoumao/MusicFree#38]
**注意事项**
- [ ] 确保已经阅读过ReadMe并*了解本软件的定位*
- [ ] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
在win11的安卓子系统下使用，APP分辨率不能自适应。希望能自适应下分辨率。可以参考头条APP

Musicfree：
![image](https://user-images.githubusercontent.com/50772707/217436147-b6f8d94f-bbbb-4c7d-88b7-3a3268e723a5.png)

今日头条：
![image](https://user-images.githubusercontent.com/50772707/217436339-b1b5cf04-f45a-48ad-aec8-9dcc7b57644d.png)

**Comment by maotoumao** [comment]
自适应应该和之前提到的横屏啥的是类似的问题... 确实没做 

我最近想一想好了😂

**Comment by Sunovn** [comment]
> 
> Musicfree： ![image](https://user-images.githubusercontent.com/50772707/217436147-b6f8d94f-bbbb-4c7d-88b7-3a3268e723a5.png)
> 
你任务栏用的是startallback吗

**Comment by milozen** [comment]
> > Musicfree： ![image](https://user-images.githubusercontent.com/50772707/217436147-b6f8d94f-bbbb-4c7d-88b7-3a3268e723a5.png)
> 
> 你任务栏用的是startallback吗

是的，11的看不习惯
