### ISSUE TITLE
是否有开发计划添加账号歌单导入功能？

### ISSUE THREAD

**Issue by non-one** [maotoumao/MusicFree#4]

**Comment by maotoumao** [comment]
导入功能现在是有的，只不过现在对应的插件里面都还没有实现；
最近两周会把插件更新一下，到时候直接重新安装下插件就好了~

**Comment by maotoumao** [comment]
网易云导入歌单功能已经可以了；如果是老版本app，先卸载网易云插件，然后从网络安装插件， 输入https://gitee.com/maotoumao/MusicFreePlugins/raw/master/netease.js
即可；
如果是新版(0.0.1-alpha.5)app，可以直接在插件页更新网易云插件就可以使用导入功能了
![image](https://user-images.githubusercontent.com/31655147/196476342-7ecb474d-669e-414e-9554-32a7b8ca5355.png)
