### ISSUE TITLE
[FEATURE] 网易云（或其他平台）的非歌单入口的支持

### ISSUE THREAD

**Issue by xiamubobby** [maotoumao/MusicFree#40]
**注意事项**
- [v] 确保已经阅读过ReadMe并*了解本软件的定位*
- [v] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
音乐软件的专辑页面和艺人热曲首页逻辑上也是一个歌单，而且是事实上常常被用户拿来直接循环的常用“歌单”。
但由于专辑和艺人页面的接口完全不同于技术意义上的歌单，所以目前插件没有支持

**替代方案**
目前想要实现相同效果唯有进入第一方软件然后批量制作和目标专辑/艺人hot50完全一样的dummy歌单，很不方便，也很麻烦。因为享用MF来作为集中了的歌单维护中心的话，再去各大app创建站位歌单其实比较折腾。

**其他信息**
album的接口我试着根据直觉改了一下，包括post和get的差别，url的差别，正则的差别，但始终无法成功。
我看了一下NeteaseNodeAPI那个项目，似乎album:POST接口的协议（至少返回体结构）可能和playlist:GET完全不同。本想着自己解决但是抱着app真的很难调试这些js，想着还是你们这边有完善的调试环境，所以先以issue ticket的形式爆出了。
一些其他类似的app也是偶有这个功能的，即比如识别专辑链接为一个逻辑歌单。确实并不是任何app都有支持，估计兼容协议并不是那么轻松吧。Just a thought。

**Comment by xiamubobby** [comment]
事实上这个想法并不是局限在 导入歌单 这一个流程里。因为即使是仅使用搜索功能，在mf中收藏专辑这个动作仍然表示为创新新歌单（并且无默认命名）。由于专辑和艺人页（在被访问的时间点上（如果考虑到数据更新的话））其实就是逻辑上的一张歌单。
换言之至少可以让收藏（仍然以创建歌单为实现方式）的过程透明化，因为这份歌单的默认名字对大部分用来说一定恰恰就是专辑本身的标题。

**Comment by maotoumao** [comment]
app确实是调试不方便，但是如果不涉及到原生库（比如@react-native-cookies/cookies），其他插件在node环境下的执行结果和app上的执行应该是等价的。所以直接这样执行，然后函数的返回值对应上就好了，这样调试会方便很多：（这里其实文档没写好）

![image](https://user-images.githubusercontent.com/31655147/221348866-f9308b5f-9a92-4d85-b246-8a7b16341564.png)

大概get到了你的意思，简单说：
1. 导入的内容不一定局限在创建的歌单（实现就是改插件的正则匹配和返回值）
2. 通过搜索等方式收藏专辑/作者的时候，可以把专辑名等信息作为歌单的默认名称

不知道是不是这样理解~

**Comment by xiamubobby** [comment]
嗯，多谢回复。期望Get的完全正确。不过我还没掌握你说的调试办法。亦步亦趋的还是🫠（主要是我对服务协议本身不熟悉，不借助app现有working的流程我mock不出像样的出入参），你说的办法理念我理解了。看看能不能搞一搞。
