### ISSUE TITLE
[FEATURE] 整个repo收集插件

### ISSUE THREAD

**Issue by smarttommyau** [maotoumao/MusicFree#42]
**注意事项**
- [x] 确保已经阅读过ReadMe并*了解本软件的定位*
- [x] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题* 

------

**需求描述**
用个repo收集插件，开发者直接用pull request上传
App中可以列出该repo中的插件，用户从中下载想用的插件。

**替代方案**

**其他信息**
参考漫画软件Tachiyomi 的做法。
音乐app应该也更容易处理，因为能用的音乐网站不多。

**Comment by maotoumao** [comment]
插件仓库在这里了：https://github.com/maotoumao/MusicFreePlugins

应该不会内置插件repo，毕竟或多或少都可能有点版权风险。。

**Comment by FeiYing9** [comment]
> 插件仓库在这里了：https://github.com/maotoumao/MusicFreePlugins

这段或者公众号里的使用链接，必须放到ReadMe头部，核心信息
