### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by TeresaAtlas** [maotoumao/MusicFree#45]
为什么无法下载了，上一个版本可以下载，这一个版本无法下载

**Comment by maotoumao** [comment]
具体点？提供一些复现路径之类的 我这边复现不了

**Comment by Yzcloud** [comment]
同样v0.1.0-alpha.2这个版本可以下载  最新版不行  换了下载路径也不行 雷电模拟器9.0.37(9)

**Comment by maotoumao** [comment]
> 同样v0.1.0-alpha.2这个版本可以下载 最新版不行 换了下载路径也不行 雷电模拟器9.0.37(9)

无法复现 
issue先关掉了 下个版本加个错误信息好了

![image](https://user-images.githubusercontent.com/31655147/226107747-477a5421-4a89-4dcd-898b-e6b0b028f72f.png)

![image](https://user-images.githubusercontent.com/31655147/226107782-c4e60499-874b-4180-ab13-7795fe4725d6.png)
