### ISSUE TITLE
屏幕状态栏歌词 批量网页导入歌单

### ISSUE THREAD

**Issue by Sober-depravity** [maotoumao/MusicFree#58]
作者大大 麻烦添加一下屏幕歌词或者状态栏歌词的功能，没有放下网易云和QQ音乐的唯一地方😭😭😭，要是可以支持下导入QQ 网易云音乐的歌单就完美无缺了😭😭😭，感谢作者大大

**Comment by Sober-depravity** [comment]
![IMG_20230531_022719](https://github.com/maotoumao/MusicFree/assets/135058134/2f69886d-7607-4f15-a82e-2f3f931016f5)
![IMG_20230531_022625](https://github.com/maotoumao/MusicFree/assets/135058134/6fe14dda-3c23-46ef-af98-1c6ad9bb3450)

**Comment by kissjerryfan** [comment]
同希望

**Comment by maotoumao** [comment]
QQ和网易云的歌词可以在侧边栏-插件设置里导入~ 状态栏歌词我想想办法...

**Comment by Sober-depravity** [comment]
导入歌单，已经找到啦，感谢作者大大

**Comment by NTR198710** [comment]
坐等坐着把状态栏歌词弄出来 加油

**Comment by kissjerryfan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
