### ISSUE TITLE
可以添加上form-data包吗？

### ISSUE THREAD

**Issue by MianJu28** [maotoumao/MusicFree#59]
**注意事项**
- [x] 确保已经阅读过ReadMe并*了解本软件的定位*
- [x] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
开发插件的时候需要用到FormData，内置的 npm 包中没有form-data包

**Comment by maotoumao** [comment]
FormData应该不用第三方包，插件里需要用FormData的地方直接用就好了~ 

![image](https://github.com/maotoumao/MusicFree/assets/31655147/7a72b067-bad2-4a55-b82b-aaa80a4c8299)
![image](https://github.com/maotoumao/MusicFree/assets/31655147/b556b750-c9a4-409d-a682-2ed210dc1780)
