### ISSUE TITLE
[FEATURE] 大佬，能不能开发个从外部导入歌单的功能，十分感谢

### ISSUE THREAD

**Issue by peter-liu-admin** [maotoumao/MusicFree#65]
**注意事项**
- [ ] 确保已经阅读过ReadMe并*了解本软件的定位*
- [ ] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

**需求描述**
请详细描述一下需求场景，以及可能导致的问题；以及你预期的解决方案或效果

**替代方案**
如果无法实现，请描述一下预期的替代方案或最低期望

**其他信息**
是否能提供一些其他的帮助，包括但不限于代码、UI、测试 ... 如果有的话，辛苦描述一下，感谢~

**Comment by maotoumao** [comment]
现有功能 不过入口比较深：
侧边栏-插件设置-点击某一个插件展开
如果有导入外部歌单功能的话会有导入歌单的按钮



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月24日 20:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] [FEATURE] 大佬，能不能开发个从外部导入歌单的功能，十分感谢 (Issue #65) |

注意事项

确保已经阅读过ReadMe并了解本软件的定位
确保你的新需求/想法合理合法，且不是因为无解决方案的众口难调导致的个例问题

需求描述
请详细描述一下需求场景，以及可能导致的问题；以及你预期的解决方案或效果

替代方案
如果无法实现，请描述一下预期的替代方案或最低期望

其他信息
是否能提供一些其他的帮助，包括但不限于代码、UI、测试 ... 如果有的话，辛苦描述一下，感谢~

**Comment by peter-liu-admin** [comment]
ok感谢你
