### ISSUE TITLE
Environment error

### ISSUE THREAD

**Issue by lllomh** [maotoumao/MusicFree#67]

**Comment by lllomh** [comment]
新建的项目 是可以跑起来的  你这个就不行了  为啥

**Comment by maotoumao** [comment]
咋跑的，直接运行了android文件夹？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月30日 05:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [maotoumao/MusicFree] [BUG] 开发环境运行后报错 (Issue #67) |

新建的项目 是可以跑起来的 你这个就不行了 为啥

**Comment by lllomh** [comment]
这是来自QQ邮箱的自动回复邮件。你好，由于邮件较多，三天内会尽快给你回复。

**Comment by lllomh** [comment]
在主目录执行 npm run android, 或者 yarn android 从运行到报错的过程，  虚拟机都是通的。 新建的项目可以跑得动。

你看看   
![dmeo](https://github.com/maotoumao/MusicFree/assets/20123291/74a4ceee-5b45-4862-8a7d-887a481a47dc)

**Comment by maotoumao** [comment]
我也不太清楚= = 是不是你安卓sdk没装好 
![image](https://github.com/maotoumao/MusicFree/assets/31655147/3f3b6f81-7e77-40bf-9cc9-95874047e9bb)

随便google了几个答案 要不试试
https://www.jianshu.com/p/e4abcaf3aab3
https://blog.csdn.net/zjc_null/article/details/88049323

**Comment by lllomh** [comment]
Gone

**Comment by lllomh** [comment]
This is an auto-reply email.Hi, due to the high volume of emails, I will get back to you as soon as possible within three days.
