### ISSUE TITLE
[BUG] 保存歌单的时候多次出现保存0首 第一次不会出现 第二次打开的时候出现

### ISSUE THREAD

**Issue by StevenCoober** [maotoumao/MusicFree#81]
不知道为啥，是保存在线上还是啥的，第二次打开出现保存的歌单是0首歌

**Comment by maotoumao** [comment]
能稳定复现嘛？给个录屏吧~

**Comment by StevenCoober** [comment]
https://github.com/maotoumao/MusicFree/assets/9156073/5c31dfda-0b8e-4602-9236-67e074d33117
视频已经上传了

**Comment by StevenCoober** [comment]
先前是84首,添加后还是84首,歌单也是添加歌单会出现0首,可能我保存的歌曲太多？
