### ISSUE TITLE
歌单内歌曲编号显示异常

### ISSUE THREAD

**Issue by Sean-Melchizedek** [maotoumao/MusicFree#9]
如图所示，左侧的歌曲编号显示部分不完整，可能是适配问题。
![e99ed6f577dc2a977fd05daaae0fe53](https://user-images.githubusercontent.com/34616892/197095653-00fcf7a0-2d86-435d-81f4-a6df30486223.jpg)
![bd24373073f2c929c729c102002788d](https://user-images.githubusercontent.com/34616892/197095667-cef5839b-a4bb-4b43-af70-b03dc3f306d0.jpg)

这是我手机的参数：
![45cc6a1117a0356e0a99b3c4e0bc735](https://user-images.githubusercontent.com/34616892/197095866-ab8a0cdb-5b2c-461d-96bd-17a28cdd8ffa.jpg)

祝好！

**Comment by maotoumao** [comment]
看样子是适配问题～ 感谢反馈 周末修掉～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月21日 10:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/MusicFree] 歌单内歌曲编号显示异常 (Issue #9) |

如图所示，左侧的歌曲编号显示部分不完整，可能是适配问题。



这是我手机的参数：


祝好！

**Comment by maotoumao** [comment]
可以试试新版本看问题还在不在~ 调整了一下字体：
https://gitee.com/maotoumao/MusicFree/releases/download/v0.0.1-alpha.6/app-release.apk

**Comment by Sean-Melchizedek** [comment]
感谢大佬的及时更新，有一定的改善，但没完全改善:joy:
![ce62428d56380ec11236c4610abaf38](https://user-images.githubusercontent.com/34616892/198486575-6ec76cc8-8cd6-4b43-a876-b89f0f8b42e2.jpg)
![83cf4bd8d69a633e91d7eda0e50572f](https://user-images.githubusercontent.com/34616892/198486623-9a703000-f5e5-40e3-a48e-e8bfd97c95c1.jpg)
![c79d654c9cfb9cde5c7b5ec1a428c1f](https://user-images.githubusercontent.com/34616892/198486667-ff127a52-b0d0-40f2-83e9-1cba7fbb10ee.jpg)

**Comment by maotoumao** [comment]
噗 感觉是斜体字有点问题

我再调一下大小就好了～😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月28日 11:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [maotoumao/MusicFree] 歌单内歌曲编号显示异常 (Issue #9) |

感谢大佬的及时更新，有一定的改善，但没完全改善😂

**Comment by Sean-Melchizedek** [comment]
我今天发现可以用这个直接搜索B站上up主的视频音频，太太太好用了哥!
请在beta版本中添加打赏二维码！
