### ISSUE TITLE
[BUG] 随机播放问题

### ISSUE THREAD

**Issue by viphanf** [maotoumao/MusicFree#90]
**注意事项**
- [ ] 确保该bug可能是软件的本身问题，不是由于插件导致（如搜索结果不全，无法导入等都属于插件问题）；如果是插件问题请去对应第三方插件仓库提issue。
- [ ] 确保已经搜索过issue区，并阅读过QA

---

**问题描述**
不能随机播放

**详细的复现步骤**
切换随机播放只是打乱了列表，点击下一首，只是播放列表的下一首

**预期行为**
随机播放下一首

**截图**
附带一些截图/录屏吧，如果方便的话打开侧边栏-基本设置-记录详细日志，复现之后贴一下Android/data/fun.upup.musicfree/files/log/trace-log.log下的日志（完成之后记得删掉，不然时间长了会卡）

**其他信息:**
 - OS: [e.g. Android12]
 - 版本号 [e.g. v0.1.0-alpha.0]

**Comment by maotoumao** [comment]
设计如此 先不改了。。
如果切换随机播放的时候不改变原有列表顺序 那使用起来也不会感知到是真随机还是打乱列表 效果一样的
