### ISSUE TITLE
AndroidStudio dev 模拟器运行进不了界面

### ISSUE THREAD

**Issue by wencyGit** [maotoumao/MusicFree#94]
![image](https://github.com/maotoumao/MusicFree/assets/21151964/dde85315-3274-404d-8f8a-86033ccaaee1)
![image](https://github.com/maotoumao/MusicFree/assets/21151964/c1b478a0-deb7-40de-abed-827183dfb17c)

- AndroidStudio运行启动打开app卡在这里，模拟器是安卓13版本，请问用运行需要哪些版本呢？

**Comment by maotoumao** [comment]
不好意思没注意看😂。。。
这一步应该是卡在了bootstrap之前，src\entry\bootstrap.ts路径下：
![image](https://github.com/maotoumao/MusicFree/assets/31655147/2d16f6b2-bf6f-4d6d-911f-5b22776c424d)

可以重启一下，或者看下log~ 按理说到这一步应该没啥问题了
